hydra-22: Add liquidity modal
galacticcouncil/Basilisk-mining-ui pull request #11
Opened 2022-08-16 10:47 UTC by patricia-cleevio

2022-08-16 11:57 UTC, fobsivac requested changes

2022-08-16 11:57 UTC, fobsivac commented on src/components/AssetInput/AssetInput.styled.ts
> +export const StyledInput = styled.input<{ error?: string; unit?: string }>`
`unit` prop isn't used here, is that ok?

2022-08-16 11:57 UTC, fobsivac commented on src/components/AssetInput/AssetInput.tsx
> +        width={p.width || 300}
I would remove the default `300` value for this and rather do `width: 100%;` if no fixed width is provided, so the input can be better used inside other dynamic containers

2022-08-16 11:57 UTC, fobsivac commented on src/components/AssetInput/AssetInput.tsx
> +        mb={5}
I think this margin should also be handled in the parent component - if there are other inputs below this one, the parent should handle the margins, it's a bit more flexible

2022-08-16 11:57 UTC, fobsivac commented on src/components/Typography/Text/Text.tsx
> +  children?: string | number
could we make this just `ReactNode`? in case an icon or something would be inside, or when a value like `{percentage}%` is put in, typescript doesn't like that since it considers this multiple children (same with `Text` component)

2022-08-16 11:57 UTC, fobsivac commented on src/components/AssetInput/AssetInput.tsx
> +import { MarginProps, SizeProps } from "common/styles"
most of the `AssetInput` seems to be copied from the `Input` component - do you think we could merge these?

2022-08-16 11:57 UTC, fobsivac commented on src/pages/FarmsPoolsPage/PoolCard/mainContent/ActionButtons/AddLiquidityModal/SelectAsset/SelectAsset.tsx
> +  asset: string
`nitpick`: imo `selected/onSelect` or `value/onChange` would be the more "standard" names for these, but you can keep these if you want

2022-08-16 12:06 UTC, patricia-cleevio commented on src/components/AssetInput/AssetInput.tsx
> +import { MarginProps, SizeProps } from "common/styles"
Well most of it is very similar styling, however i feel like separating the different use cases in one component would be much harder to read, than use it as a separate component. The whole input lays out differently, even the text-align differs, unit is in one line, dollars are bellow etc. Also nit sure about logic, might be that the dollar calculation that is currently fixed number will be calculated on value change with provided conversion  etc.

2022-08-16 12:18 UTC, fobsivac commented on src/components/AssetInput/AssetInput.tsx
> +import { MarginProps, SizeProps } from "common/styles"
hmm, I guess you're right, let's leave it separate for now

2022-08-16 13:07 UTC, dqbd requested changes

2022-08-16 13:07 UTC, dqbd commented on src/components/Typography/Text/Text.tsx
> +  text?: string | number
Use `ReactNode` instead, if we're just passing values to render via React.

2022-08-16 13:07 UTC, dqbd commented on src/components/Typography/Text/Text.tsx
> +  text?: string | number
Also, why there are two props used for rendering text: `children` and `text`? Shouldn't there be only 1 prop for that?

2022-08-16 13:07 UTC, dqbd commented on src/components/Button/Button.styled.ts
> +
I would consider using Styled System instead of rolling own variables and conventions. Especially around responsivity, which is not handled in this project at the moment.

https://styled-system.com/

2022-08-16 13:19 UTC, patricia-cleevio commented on src/components/Button/Button.styled.ts
> +
Sure, deserves separate jira issue then.

2022-08-16 13:22 UTC, dqbd commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
I believe it is still in this scope, as this MR is adding these icons. CRA is already configured to support SVG; see the documentation here: 

https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

2022-08-16 13:23 UTC, dqbd commented on src/components/Typography/Text/Text.tsx
> +  text?: string | number
Sure, let's keep it then 😄

2022-08-16 13:35 UTC, patricia-cleevio commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
I understand, however in this PR i added 2 icons, but the changes you request would mean i have to redo ALL of the icons and the usage of them, redo of props in components that use them etc, so basically almost the whole workspace. So i kinda disagree its in the scope of this PR, it requires discussion since i prefer this usage anyway and it requires Filips input as well, and i guess hierarchy meeting when it comes to components.

2022-08-16 13:36 UTC, dqbd commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
No, I'm not asking about converting all icons, I'm asking here to convert 1 icon.

2022-08-16 13:38 UTC, patricia-cleevio commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
When i change this icon to svg instead of current approach, the types in place where its implemented wont match, do you get that?

2022-08-16 13:40 UTC, patricia-cleevio commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
And the fact that i disagree with your approach stays, its up for discussion, therefore using current approach throughout the app is in the scope, and changing approach is out of the scope.

2022-08-16 13:53 UTC, dqbd commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
I'm sorry, but have you tried changing the SVGs at all? `KaruraIcon` and `SakuraIcon` are collectively used in exactly 1 place, so I still don't see a reason, why new icons are not done properly. 

One could argue for the sake of argument, that `BasiliskIcon` might be complicated to refactor and could be done in a separate PR. But the argument provided here of invalid types is just wrong, as I've tried just replacing all the imports and it works as expected.

2022-08-16 13:57 UTC, patricia-cleevio commented on src/pages/FarmsPoolsPage/PoolCard/mainContent/ActionButtons/AddLiquidityModal/SelectAsset/SelectAsset.tsx
> +            {getFormattedNumber(p.balance)}
So, if i understand correctly... You want to add react-intl, library that specializes in localization of banking currencies, to crypto project, where its basically standard to only refer to USD, bcs you dont like that the function to format numbers by adding space after 3 digits, is not... what? centralised in separate library?

2022-08-16 13:59 UTC, patricia-cleevio commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
Doesn't change the fact that i prefer current approach and therefore we're still waiting for Filips input and rest of the icons is not in the scope, so it might as well be separate issue and not split in two.

2022-08-16 14:47 UTC, fobsivac commented on src/pages/FarmsPoolsPage/PoolCard/mainContent/ActionButtons/AddLiquidityModal/SelectAsset/SelectAsset.tsx
> +            {getFormattedNumber(p.balance)}
I think David means the [Intl object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl), not an external library. I agree that would be better as well, it handles a lot of work for us in terms of formatting with currencies and locales in mind. it's used on our other projects as well, Driverama for example.

2022-08-16 15:09 UTC, fobsivac commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
imo leaving the icons as .svg files directly is a simpler approach - we can just put .svg files into the project and use them, then we don't need to convert the props into valid react and wrap the svg in a function (at least I don't think there's a benefit in doing that)

2022-08-16 15:14 UTC, patricia-cleevio commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
It allows for more versatile approach, so when component accepts ReactNode as children, you dont have to implement different approach when it gets svg as a child...?

2022-08-16 15:16 UTC, patricia-cleevio commented on src/pages/FarmsPoolsPage/PoolCard/mainContent/ActionButtons/AddLiquidityModal/SelectAsset/SelectAsset.tsx
> +            {getFormattedNumber(p.balance)}
im still very unclear on need to implement localization in crypto app. You dont transfer it into Euros or something else. The only currency you work with are american dollars, and the formatting used in the project based on design isnt standard en-us format.

2022-08-16 15:17 UTC, patricia-cleevio commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
What is benefit of redoing it at this point to .svg?

2022-08-16 16:05 UTC, fobsivac commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
benefit is the scalability of the app which is something we should keep in mind with this project for the future

2022-08-17 06:15 UTC, patricia-cleevio commented
Since I'm failing to see any constructive feedback on features INTRODUCED in this merge request, i consider it reviewed and ready for merge. Other discussions can continue in separate thread dedicated to it(in channels better fit for such internal discussion), where we can clarify under whose command visual aspect of things, and UI components as such fall under. Thank you.

2022-08-17 06:36 UTC, fobsivac commented on src/assets/icons/tokens/SakuraIcon.tsx
> +export const SakuraIcon = () => (
scalability in my view means making solutions which account for future possibilities and makes maintenance easier, so when i think it's simpler to add and use the svgs, then it will save us time in the long run. this is a minor thing of course, but that's the idea

2022-08-17 06:39 UTC, fobsivac commented on src/pages/FarmsPoolsPage/PoolCard/mainContent/ActionButtons/AddLiquidityModal/SelectAsset/SelectAsset.tsx
> +            {getFormattedNumber(p.balance)}
it's a very simple change

2022-08-17 06:47 UTC, patricia-cleevio commented on src/pages/FarmsPoolsPage/PoolCard/mainContent/ActionButtons/AddLiquidityModal/SelectAsset/SelectAsset.tsx
> +            {getFormattedNumber(p.balance)}
Im not disagreeing, im just stating that its out of the scope, the function for number formatting wasnt introduced in this PR that is "add liquidity modal" and if we want to do open source approach, we have to have clear understanding that PRs have to be as small as possible and CR has to be very much on topic. Open separate jira issue for implementing Intl as formatting tool in getFormattedNumber function and be my guest to do it right away

2022-08-17 08:17 UTC, dqbd commented
Agreed, merging.

2022-08-17 08:17 UTC, merged