feat(HYDRA-179): add aUSD conversion to select asset input
galacticcouncil/Basilisk-mining-ui pull request #110
Opened 2022-10-13 14:22 UTC by dqbd

2022-10-13 15:58 UTC, obsivac-cleevio requested changes

2022-10-13 15:58 UTC, obsivac-cleevio commented on src/sections/pools/pool/modals/addLiquidity/assetSelect/PoolAddLiquidityAssetSelect.tsx
> +    if (!props.value || props.asset === aUSD.data?.id) return null
myslim ze v pripade aUSD muzeme klidne zobrazit i dollarovou castku, bude sice stejna ale lepsi nez nic

2022-10-14 08:40 UTC, vkulinich-cl approved these changes

2022-10-14 09:52 UTC, obsivac-cleevio approved these changes

2022-10-14 09:53 UTC, merged