feat(HYDRA-138): Added tabs
galacticcouncil/Basilisk-mining-ui pull request #132
Opened 2022-10-21 09:33 UTC by tomashapl1

2022-10-21 10:13 UTC, obsivac-cleevio requested changes

2022-10-21 10:13 UTC, obsivac-cleevio commented on src/components/Button/Button.styled.ts
> +            :hover {
`hover` a `active` states by mely byt podle designu stejne

![image](https://user-images.githubusercontent.com/111859113/197171187-15433fc7-65de-4139-8e17-19cea3085b1f.png)

2022-10-21 10:13 UTC, obsivac-cleevio commented on src/components/Button/Button.styled.ts
> +              transition: background ${theme.transitions.default};
rozsiril bych na `transition: all ${theme.transitions.default};` kvuli barve textu

2022-10-21 11:55 UTC, obsivac-cleevio requested changes

2022-10-21 11:55 UTC, obsivac-cleevio commented on src/sections/wallet/header/WalletHeader.tsx
> +        sx={{ flex: "row", justify: "space-between", align: "center", pb: 25 }}
padding by mel byt 16px

2022-10-21 12:07 UTC, tomashapl1 commented on src/assets/icons/TransactionsIcon.svg
> +<path d="M10.6907 10.8718C10.6907 10.4401 10.9507 10.0517 11.3491 9.88585C11.7475 9.72082 12.2067 9.8125 12.5118 10.1175C12.8168 10.4226 12.9085 10.8818 12.7435 11.2802C12.5776 11.6786 12.1892 11.938
Když to udělám takhle, tak ta barva je opravdu jiná, než v designu

2022-10-25 07:33 UTC, vkulinich-cl requested changes

2022-10-25 07:33 UTC, vkulinich-cl commented on src/components/Button/Button.styled.ts
> +  text-transform: ${({ transform }) => (transform ? transform : "uppercase")};
${({ transform }) => (transform ?? "uppercase")}

2022-10-26 08:09 UTC, merged