Feat added your vesting table
galacticcouncil/Basilisk-mining-ui pull request #143
Opened 2022-11-01 14:48 UTC by tomashapl1

2022-11-02 11:20 UTC, obsivac-cleevio requested changes

2022-11-02 11:23 UTC, obsivac-cleevio requested changes

2022-11-03 10:14 UTC, tomashapl1 commented on src/sections/wallet/vesting/WalletVestingSchedule.tsx
> +              tOptions={{ num, denom }}
Ona tam je, ale je malá, poznáš to podle USD

2022-11-04 08:46 UTC, obsivac-cleevio commented on src/sections/wallet/vesting/WalletVestingSchedule.tsx
> +              tOptions={{ num, denom }}
ah, my bad

2022-11-04 09:57 UTC, obsivac-cleevio requested changes

2022-11-04 09:57 UTC, obsivac-cleevio commented on src/sections/wallet/vesting/WalletVestingSchedule.styled.ts
> +  box-sizing: border-box;
jeste toto prosim zapracovat

2022-11-04 09:57 UTC, obsivac-cleevio commented on src/sections/wallet/vesting/WalletVestingHeader.tsx
> +          <Separator color="neutralGray500" orientation="vertical" />
jeste toto prosim zapracovat

2022-11-07 09:05 UTC, obsivac-cleevio approved these changes

2022-11-07 09:10 UTC, merged