fixed usd value in asset select modal
galacticcouncil/Basilisk-mining-ui pull request #193
Opened 2022-11-27 12:03 UTC by obsivac-cleevio

2022-11-28 10:52 UTC, dqbd requested changes

2022-11-28 10:52 UTC, dqbd commented on src/sections/assets/AssetsModalRow.tsx
> +                fixedPointScale: asset.data.decimals,
Tady by se měl použít ten asset, který přísluší tomu USD pegu

2022-11-29 09:16 UTC, obsivac-cleevio commented on src/sections/assets/AssetsModalRow.tsx
> +                fixedPointScale: asset.data.decimals,
urcite? takto to myslim nikde nedelame, usd hodnotu ziskame jenom vynasobenim spot price, decimal places zustavaji puvodni

2022-11-29 10:16 UTC, dqbd approved these changes

2022-11-29 10:16 UTC, merged