feat: setAsFeePayment
galacticcouncil/Basilisk-mining-ui pull request #207
Opened 2022-11-28 14:40 UTC by tomashapl1

2022-12-01 11:44 UTC, obsivac-cleevio requested changes
nejde mi nastavit bsx jako fee payment asset, je mozne ze by mel byt vzdy jako moznost ikdyz neni vracen z `multiTransactionPayment.acceptedCurrencies`?

2022-12-01 13:38 UTC, tomashapl1 commented
> nejde mi nastavit bsx jako fee payment asset, je mozne ze by mel byt vzdy jako moznost ikdyz neni vracen z `multiTransactionPayment.acceptedCurrencies`?

Tady čekám ještě na odpověď

![image](https://user-images.githubusercontent.com/104817596/205067197-5f0e0439-ab0b-4305-a6da-e67c04e244e9.png)

2022-12-02 08:38 UTC, tomashapl1 commented
Tak nativní asset se nevrací z API, nicméně může být použit jako payment asset fee. Manuálně ho nyní přidávám do acceptedCurrencies pole

2022-12-02 09:17 UTC, obsivac-cleevio approved these changes

2022-12-02 09:17 UTC, merged