Fixed connect wallet modal styling
galacticcouncil/Basilisk-mining-ui pull request #213
Opened 2022-11-30 11:03 UTC by vkulinich-cl

Fixes #74

2022-11-30 11:54 UTC, dqbd requested changes

2022-11-30 11:54 UTC, dqbd commented on src/sections/wallet/connect/accountSelect/item/WalletConnectAccountSelectItem.styled.ts
> +          -webkit-mask: linear-gradient(#fff 0 0) content-box,
I don't like how the corners are jagged, can we get rid of webkit mask? It seems like it causes the rendering issues

![CleanShot 2022-11-30 at 12 53 50](https://user-images.githubusercontent.com/1443449/204789686-a34df666-7abd-495b-8603-ad460ad8fc5f.png)

2022-12-01 10:19 UTC, obsivac-cleevio approved these changes

2022-12-01 10:21 UTC, dqbd approved these changes

2022-12-01 10:21 UTC, merged