Added tooltip for no USD price value
galacticcouncil/Basilisk-mining-ui pull request #214
Opened 2022-11-30 13:09 UTC by vkulinich-cl

Fixes #161

2022-12-01 10:28 UTC, obsivac-cleevio approved these changes

2022-12-01 10:28 UTC, obsivac-cleevio commented on src/components/InfoTooltip/InfoTooltip.styled.ts
> +  all: unset;
je toto nutne?

2022-12-01 10:29 UTC, dqbd requested changes

2022-12-01 10:29 UTC, dqbd commented on src/sections/pools/pool/details/PoolValue.styled.ts
> +  :hover {
_nit_: Ta ikonka by měla být zapnutá i když na ní uživatel nedělá hover (viz `[data-state*="open"]`)

2022-12-01 11:30 UTC, vkulinich-cl commented on src/components/InfoTooltip/InfoTooltip.styled.ts
> +  all: unset;
ano, bez toho jsou tam styly button komponenty

2022-12-01 11:30 UTC, vkulinich-cl commented on src/sections/pools/pool/details/PoolValue.styled.ts
> +  :hover {
ale ted ta ikona nema tento attribut ale jeji button parent node

2022-12-01 11:35 UTC, dqbd commented on src/sections/pools/pool/details/PoolValue.styled.ts
> +  :hover {
To by neměl být problém?

`[data-state*="open"] > &`

2022-12-05 09:57 UTC, dqbd approved these changes
lgtm

2022-12-05 09:57 UTC, merged