Reworked Icons
galacticcouncil/Basilisk-mining-ui pull request #267
Opened 2023-01-25 10:19 UTC by vkulinich-cl

-Reworked multiple icons, added space between icons
-Fixed console log errors

2023-01-30 08:57 UTC, tomashapl1 requested changes

2023-01-30 08:57 UTC, tomashapl1 commented on src/sections/pools/pool/position/farm/PoolPositionFarmRedeposit.tsx
> +      <div css={{ "> svg": { width: 28, height: 28 } }}>{asset.data.icon} </div>
Nebylo by lepší tady použít `<Icon ... />`

2023-01-30 12:53 UTC, dqbd approved these changes

2023-01-31 08:39 UTC, tomashapl1 approved these changes

2023-01-31 08:44 UTC, merged