Reworked claimable farm value
galacticcouncil/Basilisk-mining-ui pull request #273
Opened 2023-01-27 16:18 UTC by vkulinich-cl

Fixes #269

2023-01-30 09:06 UTC, tomashapl1 requested changes

2023-01-30 09:06 UTC, tomashapl1 commented on src/sections/pools/farm/claim/PoolFarmClaim.tsx
> +            i18nKey="pools.allFarms.claim.toast.asset"
tady bych to udělal trochu jinak:

translation key by bylo: `pools.allFarms.claim.toast.more_assets` - `<0>{{num}}{{denom}} {{symbol}}</0> {{ nextAsset }}` 

a **nextAsset** by bylo `and <0>{{num}}{{denom}} {{symbol}}</0>`

a nebo by jsi mohl použít plurals:
https://www.i18next.com/translation-function/plurals

example:
```
"wallet.vesting.vesting_days_left_value_one": "{{ count }} day",
"wallet.vesting.vesting_days_left_value_other": "{{ count }} days"
```

2023-01-30 09:34 UTC, vkulinich-cl commented on src/sections/pools/farm/claim/PoolFarmClaim.tsx
> +            i18nKey="pools.allFarms.claim.toast.asset"
tento zpusob nejde pouzit. Protoze tech farem muze byt i 3.

2023-01-31 08:40 UTC, tomashapl1 approved these changes

2023-01-31 08:45 UTC, merged