Hide Origin Chain info
galacticcouncil/Basilisk-mining-ui pull request #275
Opened 2023-01-31 09:58 UTC by vkulinich-cl

Fix #274 
-Reworked locked values for the assets to be consistent with Hydra for both desktop and mobil views
-Hidden origin chain for liquidity positions

2023-01-31 15:25 UTC, tomashapl1 requested changes

2023-01-31 15:25 UTC, tomashapl1 commented on src/api/balances.ts
> +        amount: lock.amount.toBigNumber(),
Could we return native type ? as it was and transform in hook where are you using ?

2023-01-31 15:25 UTC, tomashapl1 commented on src/components/InfoTooltip/InfoTooltip.tsx
> +          textOnClick && e.preventDefault()
```
if(textOnClick) {
            e.preventDefault()
            e.stopPropagation()
            setContent(textOnClick)
          }
 ```

2023-01-31 15:30 UTC, vkulinich-cl commented on src/sections/pools/pool/footer/PoolFooter.tsx
> +        {claimable.data?.usd && !claimable.data?.usd.isZero() && (
I added the second conditional to fix the case when the chaining operator returns `undefined`, and in this case `!undefined` is true.

2023-02-01 08:32 UTC, tomashapl1 approved these changes

2023-02-01 08:38 UTC, merged