feat: added math package
galacticcouncil/Basilisk-mining-ui pull request #34
Opened 2022-09-07 11:54 UTC by tomashapl1

2022-09-07 12:31 UTC, obsivac-cleevio approved these changes

2022-09-07 13:07 UTC, dqbd requested changes

2022-09-07 13:07 UTC, dqbd commented on src/utils/math.ts
> +  const xyk = await import("@galacticcouncil/math/build/xyk/bundler")
Tady bych to načítal dohromady skrz Promise.all

2022-09-08 17:36 UTC, tomashapl1 commented on src/utils/math.ts
> +  const xyk = await import("@galacticcouncil/math/build/xyk/bundler")
Pravda, asynchroně je načíst zároveň 👍

2022-09-08 17:44 UTC, merged