Connect more fields in pool join modal
galacticcouncil/Basilisk-mining-ui pull request #36
Opened 2022-09-08 04:52 UTC by dqbd

2022-09-09 09:52 UTC, obsivac-cleevio requested changes

2022-09-09 09:52 UTC, obsivac-cleevio commented on src/api/balances.ts
> +  const safeId = typeof id === "string" ? id : id.toString()
je toto nutne? ikdyby bylo `id` string tak se nic nestane po zavolani `.toString()`

2022-09-09 09:52 UTC, obsivac-cleevio commented on src/i18n/i18n.ts
> +          const precision = BN_10.pow(BN_12)
muzeme pridat (jako vyse u amount) precision jako parametr?

2022-09-09 09:52 UTC, obsivac-cleevio commented on src/sections/pools/pool/modals/joinFarm/PoolJoinFarm.tsx
> +            value: props.farm.apr.toFixed(2),
APR zatim radeji neomezovat na dve mista, s temi testovacimi daty to je fakt male cislo tak bychom tam mel akorat `0.00%`, to nam zatim moc nerekne 😅

2022-09-09 09:52 UTC, obsivac-cleevio commented on src/utils/apr.ts
> +  const blocksPerYear = new BN(secondsInYear).div(blockTime)
nejak bych neprejmenovaval ty hodnoty nebo upravoval vzorce, schvalne jsem to nechaval stejne jako v tom navodu v notion, at vime presne odkad co je

2022-09-09 09:52 UTC, obsivac-cleevio commented on src/utils/apr.ts
> +export const useBestNumber = () => {
queries do `/api` slozky prosim, at to mame na jednom miste

2022-09-09 09:52 UTC, obsivac-cleevio commented on src/sections/pools/pool/modals/joinFarm/PoolJoinFarm.tsx
> +                .toNumber() * 100
nemeli bychom radeji to nasobeni dat jeste pred `.toNumber()`?
```
props.farm.distributedRewards
    .div(props.farm.maxRewards)
    .times(100)
    .toNumber()
```
obdobne i nize

2022-09-09 13:01 UTC, dqbd commented on src/api/balances.ts
> +  const safeId = typeof id === "string" ? id : id.toString()
Ta idea je taková, že jsem nechtěl úplně vše přemigrovat a stále ponechat `string`, jelikož bych zasahovat do vícero částí. Přidám TODO

2022-09-10 07:50 UTC, obsivac-cleevio approved these changes

2022-09-10 08:40 UTC, obsivac-cleevio requested changes

2022-09-10 08:40 UTC, obsivac-cleevio commented on src/sections/pools/pool/modals/joinFarm/PoolJoinFarm.tsx
> +          {getAssetLogo(asset.data.name)}
ikonu uz dostavas z `useAsset`

2022-09-10 08:40 UTC, obsivac-cleevio commented on src/utils/apr.ts
> +    const filteredFarms = farms.filter(
good call 👍

2022-09-10 10:19 UTC, dqbd commented on src/sections/pools/pool/modals/joinFarm/PoolJoinFarm.tsx
> +          {getAssetLogo(asset.data.name)}
nice 👍

2022-09-10 10:20 UTC, obsivac-cleevio approved these changes

2022-09-10 15:40 UTC, merged