feat: Add liquidity share token calculation
galacticcouncil/Basilisk-mining-ui pull request #38
Opened 2022-09-08 17:27 UTC by tomashapl1

2022-09-09 12:46 UTC, dqbd requested changes

2022-09-09 12:46 UTC, dqbd commented on src/api/shareToken.ts
> +  return res.toString()
Je možné vracet nativní typy a převádět to na příslušné řetězce až když to bude potřeba?

2022-09-09 12:46 UTC, dqbd commented on src/api/pools.ts
> +      const [assetA, assetB] = codec.toHuman() as string[]
Je možné vracet nativní typy a převádět to na příslušné řetězce až když to bude potřeba?

2022-09-09 12:46 UTC, dqbd requested changes

2022-09-09 12:46 UTC, dqbd commented on src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidity.tsx
> +      : BN_NAN
Je NaN rozumná hodnota? Není lepší spíše zobrazit spinner nebo nic namísto `nan`?

2022-09-12 08:57 UTC, tomashapl1 commented on src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidity.tsx
> +      : BN_NAN
Když to bude NaN - funkce `getFullDisplayBalance` zobrazí `-`

2022-09-12 09:15 UTC, obsivac-cleevio requested changes

2022-09-12 09:15 UTC, obsivac-cleevio commented on src/api/pools.ts
> +      const shareToken = await getShareToken(api, id)
nechceme radeji udelat pro share token hook a pouzivat ho, kde je treba? neni nutny zrovna pri ziskavani vsech poolu

2022-09-12 14:17 UTC, dqbd commented on src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidity.tsx
> +      : BN_NAN
Hm... rozumím, avšak mi přijde, že je lepší v tomto případě vracet `null`, což by ve `getFullDisplayBalance` dělalo to stejné AFAIK. NaN se totiž navenek tváří jako číslo z pohledu TS a čím méně explicitních NaN budeme mít, tím lépe.

2022-09-12 15:21 UTC, tomashapl1 commented on src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidity.tsx
> +      : BN_NAN
Není lepší vracet jeden typ než 2 ?
```
 BigNumber(NaN) - BigNumber než BigNumber | null
```

2022-09-13 08:42 UTC, obsivac-cleevio approved these changes

2022-09-13 12:08 UTC, tomashapl1 commented on src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidity.tsx
> +      : BN_NAN
Done ✅

2022-09-13 20:57 UTC, dqbd requested changes

2022-09-13 20:57 UTC, dqbd commented on src/api/totalIssuance.ts
> +    return BN_NAN
Tady je stále ten `BN_NAN`

2022-09-13 21:46 UTC, dqbd approved these changes

2022-09-13 21:46 UTC, dqbd commented
Ideálně se na to ještě podívej jestli to vyhovuje i tobě @tomashapl1, viz Slack

2022-09-14 07:54 UTC, merged